config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#oauth_login'

  post '/users/:id/message' => 'users#message'




  resources :workouts do
    resources :trainings, only: [:index, :new, :create]
  end
  resources :trainings
  resources :races do
    resources :trainings
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :race
  belongs_to :workout

  scope :by_workout, -> (workout_id) {where("workout_id = ?", workout_id)}

  validates :date, presence: true
  validates_associated :workout


  #accepts_nested_attributes_for :workout

  def workout_attributes=(workout_params)
    workout = Workout.find_or_create_by(workout_params)
    #workout.valid? ? self.workout = workout : self.workout
    workout_params[:name].empty? ? self.workout : self.workout = workout
  end

  def datetime
    self.date.strftime("%A, %b %d") if self.date
    #self.date.try(:strftime, "%A, %b %d")
  end

  def username
    @username ||= self.race.try(:user).try(:username)
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  def show
    @training = Training.find(params[:id])
  end

  def index
    #if it's nested
    if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id])
      @trainings = @workout.trainings
      # @trainings = current_user.trainings.by_workout(params[:workout_id])
        #load up only the trainings nested under that workout
    elsif params[:race_id] && @race = Race.find_by_id(params[:race_id])
      @trainings = @race.trainings
    else
      #keep with the same old stuff
      @trainings = Training.all
    end
  end

  def new
    if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id])
      @training = @workout.trainings.build #has_many
    else
      @training = Training.new
      @training.build_workout  #belongs_to - nested form
    end
  end

  def create
     if params[:workout_id] && @workout = Workout.find_by_id(params[:workout_id])
      @training = @workout.trainings.build(training_params)
     else
      @training = Training.new(training_params)
     end

     if @training.save
      redirect_to training_path(@training)
     else
      render :new
     end
  end

  private

  def training_params
    params.require(:training).permit(:date,:feeling, :race_id, :workout_id, workout_attributes:[:name, :category, :pace, :distance, :user_id])
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper

  def display_index_header
     if @workout
      content_tag(:h2,"Training Sessions for the  #{@workout.name} workout")
     elsif @race
       tag.h2("Training Sessions for the #{@race.title} race")
     else
      content_tag(:h1, "All Training Sessions")
     end
  end

  def display_date(t)
    "on #{t.datetime}" if t.date
  end


  def display_feeling(t)
    "and felt: #{t.feeling}"  if !t.feeling.empty?
  end

  def workout_form_option(form_builder)
    if @workout
       content_tag(:p, "Workout: #{@workout.name}")
    else
       render partial: "workoutform", locals: {f: form_builder}
    end
  end

end

app/views/trainings/_workoutform.html.erb
<%= f.label :workout_id, "Select a workout:" %>
    <%= f.collection_select :workout_id, Workout.all, :id, :name, include_blank: true    %>

     <br></br>

     <h3>Or Create a new workout:</h3>
     <%= render partial: "layouts/errors", locals: { object: @training.workout } %>


  <%= f.fields_for :workout do |w| %>
    <%= w.label :name %>
    <%= w.text_field :name %>
    <br></br>

  <%= w.label :category %>
  <%= w.select :category,options_for_select(["run", "swim", "bike", "walk", "weights", "other"]), include_blank: true  %>
    <br></br>

  <%= w.label :pace %>
  <%= w.text_field :pace %>
  <br></br>

  <%= w.label :distance, "Distance in Miles" %>
  <%= w.text_field :distance %>
    <br></br>

  <%= w.hidden_field :user_id, value: current_user.id %>
    <br></br>

  <% end %>

app/views/trainings/index.html.erb
<%= display_index_header %>

<ul>
<% @trainings.order(:date).each do |t| %>
  <li>
    <%= t.username %> completed the
    <%= link_to t.workout.name, workout_path(t.workout)%>
    while training for the <%= link_to t.race.title, race_path(t.race)%>
    <%= display_date(t) %>
    <%= display_feeling(t) %>


  </li><br>
<% end %>
</ul>

app/views/trainings/new.html.erb
<h1>Record a Training Session</h1>

<%= render partial: "layouts/errors", locals: { object: @training } %>

<%= form_for [@workout,@training] do |f| %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :feeling %>
  <%= f.text_field :feeling %>

  <br></br>

  <%= f.label :race_id %>
  <%= f.collection_select :race_id, current_user.races, :id, :title    %>

  <br></br>

  <%= workout_form_option(f) %>

  <%= f.submit%>


<% end %>

app/views/trainings/show.html.erb
<h1>Workout: <%= @training.workout.name %></h1>

<h2>Race: <%=@training.race.title%>

<h3><%= @training.workout.category %>  | <%= @training.workout.distance %> miles</h3>

<p>Date: <%= @training.date %>  </p>

<p>Feeling: <%= @training.feeling %></p>