config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#oauth_login'

  post '/users/:id/message' => 'users#message'




  resources :workouts do
    resources :trainings, only: [:index, :new, :create]
  end
  resources :trainings
  resources :races do
    resources :trainings
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :trainings
  has_many :races, through: :trainings
  belongs_to :user

  validates :name, :distance, presence: true

  scope :order_by_popularity, -> { Workout.left_joins(:trainings).group(:id).order("count(trainings.workout_id) desc") }
  #order by how many training sessions
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show]

  def index
    @workouts = Workout.order_by_popularity
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create
     @workout = current_user.created_workouts.build(workout_params)
     if @workout.save
      redirect_to workout_path(@workout)
     else
      render :new
     end
  end

   private

   def workout_params
    params.require(:workout).permit(:pace, :distance, :name, :category)
   end

   def set_workout
      @workout = Workout.find_by(id: params[:id])
      redirect_to workouts_path if !@workout
   end

end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/index.html.erb
<h1>All Workouts</h1>

<ul>
<% @workouts.each do |workout| %>
<li>
  <strong><%= workout.name %></strong> -
  <%=workout.distance %> miles  -
  <%=workout.pace %> - added by: <%= workout.user.username %> |
  <%= link_to "See all training sessions", workout_trainings_path(workout)%> |
  <%= link_to "Add a training session", new_workout_training_path(workout)%> |
  <%= workout.trainings.size %>

</li>

<% end %>
</ul>

app/views/workouts/new.html.erb
<h1>Add a New Workout</h1>
<%= form_for @workout do |f| %>

 <%= f.label :name %>
  <%= f.text_field :name %>
    <br></br>

  <%= f.label :category %>
  <%= f.select :category,options_for_select(["run", "swim", "bike", "walk", "weights", "other"]), include_blank: true  %>
    <br></br>

  <%= f.label :pace %>
  <%= f.text_field :pace %>
  <br></br>

  <%= f.label :distance, "Distance in Miles" %>
  <%= f.text_field :distance %>
    <br></br>


    <h4>Record a Training Session for this workout:</h4>
    <%= f.fields_for :trainings do |t|%>

      <%= t.label :race_id %>
      <%= t.collection_select :race_id, current_user.races, :id, :title    %>

      <%= t.label :date %>
      <%= t.date_field :date %>

      <%= t.label :feeling %>
      <%= t.text_field :feeling %>

      <br></br>


    <% end %>
  <%= f.submit%>

<% end %>

app/views/workouts/show.html.erb
<h1><%= @workout.name %></h1>

<h3><%= @workout.category %></h3>


<p><%=@workout.distance %> miles</p>

<%=@workout.pace %>