config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#oauth_login'

  post '/users/:id/message' => 'users#message'




  resources :workouts do
    resources :trainings, only: [:index, :new, :create]
  end
  resources :trainings
  resources :races do
    resources :trainings
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :user
  has_many :trainings
  has_many :workouts, through: :trainings

  validates :title, :distance, :category, presence: true
  validates :distance, numericality: { message: "%{value} must be a number" }
  #validates_uniqueness_of :title, scope: :distance

  validate :not_a_duplicate

  #Race.longest_two_races
  #@current_user.races.longest_two_races

  scope :order_alpha_reverse, -> { order(title: :desc)}
  scope :longest_two_races, -> { order(distance: :desc).limit(2)}
  scope :distance_search, -> (search_distance){ where("distance > ?", search_distance)}



  # def self.longest_three_races
  # end

  def not_a_duplicate
    #instance method
    if Race.find_by(title: title, distance: distance, category: category, user_id: user_id)
      errors.add("race", "has already been used - this race has already been created")
    end
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
    @races = current_user.races
  end

  def show
    @race = Race.find_by(id: params[:id])
  end


  def new
    @race = Race.new
  end

  def create
    @race = current_user.races.build(race_params)
    if @race.save
      redirect_to race_path(@race)
    else
      render :new
    end
  end

  def edit
    @race = Race.find_by(id: params[:id])
  end

  def update
    @race = Race.find_by(id: params[:id])
    if @race.update(race_params)
      redirect_to race_path(@race)
    else
      render :edit
    end
  end

  private

  def race_params
    params.require(:race).permit(:title, :distance, :category)
  end

end

app/helpers/races_helper.rb
module RacesHelper


end

app/views/races/_form.html.erb
<%= form_for @race do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br></br>

  <%= f.label :distance, "Distance in Miles" %>
  <%= f.number_field :distance, min: 0 %>
  <br></br>

  <%= f.label :category %>
  <%= f.select :category,options_for_select(["run", "swim", "bike", "triathalon", "other"]), include_blank: true %>

    <br></br>

  <%= f.submit%>

<% end %>

app/views/races/edit.html.erb
<h1>Edit <%= @race.title %></h1>

<%= render "form" %>

app/views/races/index.html.erb
<h1>Your Races</h1>

<% @races.each do |race|%>
  <div>
    <h3><%= link_to race.title, race_path(race) %> </h3>
    <p>Type: <%= race.category %> |
    Distance: <%= race.distance %> miles </p>
  </div><br>
<% end %>

app/views/races/new.html.erb
<h1>Create a new Race</h1>

<%= render partial: "layouts/errors", locals: { object: @race } %>


<%= render "form" %>

app/views/races/show.html.erb
<h1><%= @race.title %></h1>

<p><strong>Type:</strong> <%= @race.category %> </p>
<p><strong>Distance:</strong> <%= @race.distance %> miles </p>


<%= link_to "Edit Race", edit_race_path(@race) %>