config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/auth/:provider/callback' => 'sessions#oauth_login'

  post '/users/:id/message' => 'users#message'




  resources :workouts do
    resources :trainings, only: [:index, :new, :create]
  end
  resources :trainings
  resources :races do
    resources :trainings
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rpb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
    <nav class='navbar'>
      <%= link_to 'Logout', '/logout', method: :delete, class:'button'%>
      <%= link_to 'My Races', races_path , class:'button'%>
      <%= link_to 'Add a Race', new_race_path , class:'button'%>
      <%= link_to 'Add a Workout', new_workout_path , class:'button'%>
      <%= link_to 'All Workouts', workouts_path, class:'button' %>
      <%= link_to 'Add a Training Session', new_training_path, class:'button' %>
      <%= link_to 'My Training Sessions', trainings_path, class:'button' %>
    </nav>
    <% else %>
      <%= link_to 'Log In', login_path %>
    <% end %>
    <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>